server:
  port: 8081
spring:
  profiles:
    active: ${SPRING_PROFILES_INCLUDE:dev}
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://127.0.0.1:8999}
  cloud:
    config:
      label: ${SPRING_CLOUD_CONFIG_LABEL:master}
      username: ${SPRING_CLOUD_CONFIG_USERNAME:geek_user}
      password: ${SPRING_CLOUD_CONFIG_PASSWORD:geek_pass}
jwt:
  token:
    expired: 86_400_000
    secret: 'jwtsecret'


